# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqsf < Formula
  desc "sqsf is a tool to receive AWS SQS messages like `tail -f`."
  homepage "https://github.com/winebarrel/sqsf"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/sqsf/releases/download/v1.1.1/sqsf_1.1.1_darwin_arm64.tar.gz"
      sha256 "fb91daf48e9bc37442d6abd5474e62907bc92a6c94a4bd9a18df28b536d40d1f"

      def install
        bin.install 'sqsf'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/sqsf/releases/download/v1.1.1/sqsf_1.1.1_darwin_amd64.tar.gz"
      sha256 "26b049ab935de0dfc650e7998c942c44e46ba26ec2a06eb90c8aa325b10ad7bb"

      def install
        bin.install 'sqsf'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/sqsf/releases/download/v1.1.1/sqsf_1.1.1_linux_arm64.tar.gz"
      sha256 "2b6395a0b4f02c52ff5c69e7598bc597477f7bccba179918f01068d023015576"

      def install
        bin.install 'sqsf'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/sqsf/releases/download/v1.1.1/sqsf_1.1.1_linux_amd64.tar.gz"
      sha256 "e8b6de84f2b17b73aa75a7fda58b2aaccbe1807c1b4affbeab03349eec18fcc6"

      def install
        bin.install 'sqsf'
      end
    end
  end
end
